### ISSUE TITLE
Add LICENSE file and update maintainer information

### ISSUE THREAD

**Issue by Rindrics** [route06/aws-cost-cli#1]
- Take over the forked aws-cost-cli author for the following reasons:
  - To control feature additions and release timing within our organization.
  - Because the features we need may not necessarily align with Kamran's development intentions.
  - To independently increment semantic versions from the upstream repository.

**Comment by rindrics** [comment]
We'll do this by following procedure:
- Add `LICENSE` authorizing [`@kamranahmedse`](https://github.com/kamranahmedse) to express current state
- Specify route06 as an author of this forked version

**Comment by rindrics** [comment]
done in #10
